/* Comparisons and learning features; no extra library or simulated measurements. */
(function(root){
 'use strict';
 const ZONE='America/Fortaleza',CAP=3000;
 const number=n=>n.toLocaleString('pt-BR',{maximumFractionDigits:1,minimumFractionDigits:1});
 const stamp=d=>d.toLocaleString('pt-BR',{timeZone:ZONE,day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
 function valid(r,now=Date.now()){return r&&r.date instanceof Date&&Number.isFinite(+r.date)&&+r.date<=now+30000&&Number.isFinite(r.temp)&&r.temp>=-40&&r.temp<=80&&Number.isFinite(r.hum)&&r.hum>=0&&r.hum<=100;}
 function mean(items){return items.length?{temp:items.reduce((s,r)=>s+r.temp,0)/items.length,hum:items.reduce((s,r)=>s+r.hum,0)/items.length,count:items.length}:null;}
 function compare(items,mode,now=new Date()){
  const rows=items.filter(r=>valid(r,+now)).sort((a,b)=>b.date-a.date),key=StationHistory.dayKey(now),today=rows.filter(r=>StationHistory.dayKey(r.date)===key);
  if(mode==='hour'){
   const current=rows[0];if(!current)return {a:null,b:null,scope:'Precisamos de uma leitura e de outra próxima de uma hora antes.'};
   const target=+current.date-3600000,previous=rows.slice(1).filter(r=>Math.abs(+r.date-target)<=600000).sort((a,b)=>Math.abs(+a.date-target)-Math.abs(+b.date-target))[0];
   return {a:current,b:previous||null,aLabel:'Última leitura',bLabel:'Cerca de 1h antes',scope:'Leituras individuais. Tolerância de 10 minutos para encontrar o horário anterior.',detail:stamp(current.date)+(previous?' × '+stamp(previous.date):' · sem leitura próxima de uma hora antes'),stale:+now-current.date>120000};
  }
  if(mode==='days'){
   const start=+StationHistory.bounds(key).start,elapsed=+now-start,yesterday=StationHistory.shift(key,-1),endYesterday=+StationHistory.bounds(yesterday).start+elapsed;
   const previous=rows.filter(r=>StationHistory.dayKey(r.date)===yesterday&&+r.date<=endYesterday);
   return {a:mean(today),b:mean(previous),aLabel:'Hoje',bLabel:'Ontem',scope:'Médias da meia-noite até o mesmo horário nos dois dias. Dias com lacunas podem ter coberturas diferentes.',detail:'Até '+now.toLocaleTimeString('pt-BR',{timeZone:ZONE,hour:'2-digit',minute:'2-digit'})+' · média por leitura'};
  }
  const hour=r=>Number(new Intl.DateTimeFormat('en-GB',{timeZone:ZONE,hour:'2-digit',hourCycle:'h23'}).format(r.date));
  return {a:mean(today.filter(r=>hour(r)>=12&&hour(r)<18)),b:mean(today.filter(r=>hour(r)>=6&&hour(r)<12)),aLabel:'Tarde',bLabel:'Manhã',scope:'Médias de hoje: manhã das 6h às 11h59; tarde das 12h às 17h59. O período atual pode estar incompleto.',detail:'Média por leitura; horários de Canto do Buriti (UTC−3).'};
 }
 function trend(items,now=Date.now()){
  const rows=items.filter(r=>valid(r,now)&&+r.date>=now-3600000).sort((a,b)=>a.date-b.date),last=rows.at(-1);
  if(!last||now-last.date>120000)return {available:false,reason:'Aguarde uma leitura recente para acompanhar a tendência.'};
  if(rows.length<3||last.date-rows[0].date<600000)return {available:false,reason:'Precisamos de pelo menos 3 leituras distribuídas em 10 minutos.'};
  return {available:true,temp:last.temp-rows[0].temp,hum:last.hum-rows[0].hum,minutes:Math.round((last.date-rows[0].date)/60000),count:rows.length};
 }
 function records(items,dayKey){
  if(!items.length)return null;const byDay=new Map();let max=items[0],min=items[0],wet=items[0];
  for(const r of items){if(r.temp>max.temp)max=r;if(r.temp<min.temp)min=r;if(r.hum>wet.hum)wet=r;const key=dayKey(r.date),group=byDay.get(key)||[];group.push(r);byDay.set(key,group);}
  const hottest=[...byDay].map(([key,rows])=>({key,...mean(rows)})).sort((a,b)=>b.temp-a.temp)[0];return {max,min,wet,hottest};
 }

 function cleanRows(items,now=Date.now()){
  const times=new Map();for(const r of items)if(valid(r,now)&&!times.has(+r.date))times.set(+r.date,r);return [...times.values()].sort((a,b)=>a.date-b.date);
 }
 // Magnus approximation over water (WMO): pressure in hPa; absolute humidity in g/m³.
 function moisture(temp,hum){
  if(!Number.isFinite(temp)||!Number.isFinite(hum)||temp< -40||temp>60||hum<0||hum>100)return {dew:null,water:null};
  const gamma=17.62*temp/(243.12+temp),pressure=6.112*Math.exp(gamma)*hum/100,water=216.679*pressure/(temp+273.15);
  if(hum===0)return {dew:null,water};const alpha=gamma+Math.log(hum/100),dew=243.12*alpha/(17.62-alpha);return {dew:dew>=-45&&dew<=60?dew:null,water};
 }
 function recentMetrics(items,now,score){
  const rows=cleanRows(items,now),last=rows.at(-1);if(!last)return null;
  const intervals=rows.slice(1).map((r,i)=>+r.date-rows[i].date),close=intervals.filter(n=>n>0&&n<=120000).sort((a,b)=>a-b),gaps=intervals.filter(n=>n>120000);
  const cadence=close.length<2?null:close.length%2?close[(close.length-1)/2]:(close[close.length/2-1]+close[close.length/2])/2;
  const key=StationHistory.dayKey(last.date),hours=new Map();for(const r of rows){if(StationHistory.dayKey(r.date)!==key)continue;const hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:ZONE,hour:'2-digit',hourCycle:'h23'}).format(r.date));const values=hours.get(hour)||[];values.push(r);hours.set(hour,values);}
  const best=[...hours].filter(([,values])=>values.length>=3&&values.at(-1).date-values[0].date>=600000).map(([hour,values])=>({hour,count:values.length,score:values.reduce((sum,r)=>sum+score(r.temp,r.hum),0)/values.length})).sort((a,b)=>b.score-a.score||a.hour-b.hour)[0]||null;
  return {rows,last,count:rows.length,stale:now-last.date>120000,cadence,intervalCount:close.length,gapCount:gaps.length,longestGap:gaps.length?Math.max(...gaps):0,best,day:key,...moisture(last.temp,last.hum)};
 }
 function duration(ms){if(ms<60000)return number(ms/1000)+' s';if(ms<3600000)return number(ms/60000)+' min';return number(ms/3600000)+' h';}
 function bulletin(items,now,score,connected=true){
  const m=recentMetrics(items,now,score);if(!m)return null;
  return ['IMNVLab · Boletim da estação','Gerado em '+stamp(new Date(now))+' (UTC−3)','Última leitura: '+stamp(m.last.date)+' (UTC−3)','Estado: '+(!connected?'aparelho sem conexão':m.stale?'leitura desatualizada':'leitura recente'),'', 'Temperatura: '+number(m.last.temp)+' °C','Umidade relativa: '+number(m.last.hum)+'%','Conforto estimado: '+score(m.last.temp,m.last.hum)+'/100','Ponto de orvalho estimado: '+(m.dew===null?'indisponível':number(m.dew)+' °C'),'Vapor de água estimado: '+(m.water===null?'indisponível':number(m.water)+' g/m³'),'', 'Amostra: '+m.count+' leituras de '+stamp(m.rows[0].date)+' a '+stamp(m.last.date),'Intervalo mediano entre envios próximos: '+(m.cadence===null?'amostra insuficiente':duration(m.cadence)),'Pausas maiores que 2 minutos: '+(m.count<2?'amostra insuficiente':m.gapCount+(m.gapCount?' · maior: '+duration(m.longestGap):'')),'Melhor hora de conforto na amostra do dia '+m.day+': '+(m.best?String(m.best.hour).padStart(2,'0')+'h · índice médio '+number(m.best.score)+'/100':'amostra insuficiente'),'', 'As leituras carregadas podem não cobrir o dia completo. Lacunas não são preenchidas. Estimativas não são previsões nem avaliações de saúde. Dados antigos não descrevem o ambiente agora.'].join('\n');
 }
 const api={valid,mean,compare,trend,records,cleanRows,moisture,recentMetrics,bulletin};
 if(typeof module!=='undefined'&&module.exports){module.exports=api;return;}
 root.StationExplorer=api;
 const el=id=>document.getElementById(id),cache=new Map(),pending=new Map();
 let mode='hour',comparisonData=null,comparisonError=false,compareBusy=false,compareRequest=0,recordData=null;
 async function fetchPeriod(startKey,endKey,force=false){
  const key=startKey+'/'+endKey,cached=cache.get(key);if(!force&&cached&&Date.now()-cached.at<60000)return cached;
  if(pending.has(key))return pending.get(key);
  const operation=(async()=>{
   const start=StationHistory.bounds(startKey).start,end=StationHistory.bounds(endKey).start;
   const ranges=[[firebase.firestore.Timestamp.fromDate(start),firebase.firestore.Timestamp.fromDate(end)],[+start,+end],[+start/1000,+end/1000],[StationHistory.shift(startKey,-1),StationHistory.shift(endKey,1)]];
   let timer;try{
    const snapshots=await Promise.race([Promise.all(ranges.map(([from,to])=>db.collection('leituras').where('timestamp','>=',from).where('timestamp','<',to).orderBy('timestamp','desc').limit(CAP).get({source:'server'}))),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('timeout')),20000);})]);
    const all=new Map();for(const s of snapshots)for(const doc of s.docs){const d=doc.data(),r={id:doc.id,temp:d.temperatura==null?NaN:Number(d.temperatura),hum:d.umidade==null?NaN:Number(d.umidade),date:readingDate(d.timestamp)};if(valid(r)&&+r.date>=+start&&+r.date<+end)all.set(r.id,r);}
    const result={items:[...all.values()].sort((a,b)=>b.date-a.date),partial:snapshots.some(s=>s.size>=CAP),at:Date.now(),startKey,endKey};cache.set(key,result);return result;
   }finally{clearTimeout(timer);}
  })();pending.set(key,operation);try{return await operation;}finally{pending.delete(key);}
 }
 function compareRows(data){
  if(!data.a||!data.b)return '<div class="feature-empty">Não há leituras suficientes nos dois períodos. Escolha outro período ou consulte uma data em <a href="#dados">Dados</a>.</div>';
  return [['temp','Temperatura','°C'],['hum','Umidade','%']].map(([field,label,unit])=>{const delta=data.a[field]-data.b[field],flat=Math.abs(delta)<0.05;return `<div class="comparison-row"><div><span>${label}</span><strong class="delta ${flat?'steady':delta>0?'rising':'falling'}">${flat?'→':delta>0?'↑':'↓'} ${number(Math.abs(delta))} ${field==='hum'?'p.p.':'°C'}</strong></div><div><small>${data.aLabel}</small><b>${number(data.a[field])}${unit}</b></div><div><small>${data.bLabel}</small><b>${number(data.b[field])}${unit}</b></div></div>`;}).join('')+'<p class="feature-note">A seta compara o primeiro período com o segundo. p.p. significa pontos percentuais.'+(data.a.count?' '+data.a.count+' leituras × '+data.b.count+' leituras.':'')+'</p>';
 }
 function renderComparison(){
  const rows=comparisonData?.items||readings;
  const data=compare(rows,mode);
  el('comparisonScope').textContent=data.scope;
  el('comparisonResult').innerHTML=compareBusy?'<div class="feature-empty">Buscando os dois períodos…</div>':comparisonError?'<div class="feature-empty">Não foi possível consultar os períodos. Use Atualizar para tentar novamente.</div>':compareRows(data);
  el('comparisonStatus').textContent=compareBusy?'Consultando medições registradas…':comparisonError?'Verifique sua conexão. Nenhuma comparação foi calculada.':(data.detail||'')+(data.stale?' · Dados antigos: não representam o ambiente agora.':'')+(comparisonData?.partial?' · Consulta limitada: comparação da amostra, que pode estar incompleta.':'');
  el('comparisonRefresh').disabled=compareBusy;
 }
 async function loadComparison(force=false){
  const request=++compareRequest;compareBusy=true;comparisonError=false;renderComparison();const key=StationHistory.dayKey();
  try{const result=await fetchPeriod(StationHistory.shift(key,-1),StationHistory.shift(key,1),force);if(request===compareRequest){comparisonData=result;root.SiteExperience?.acceptRange(result);}}catch{if(request===compareRequest)comparisonError=true;}finally{if(request===compareRequest){compareBusy=false;renderComparison();}}
 }

 const miniState={};
 function selectMini(field,index,user=false){
  const state=miniState[field];if(!state?.rows.length)return;const i=Math.max(0,Math.min(state.rows.length-1,index)),r=state.rows[i];state.index=i;state.selected=+r.date;state.follow=i===state.rows.length-1;
  const range=el(field+'MiniRange');range.value=i;range.setAttribute('aria-valuetext',number(r[field])+(field==='temp'?' graus Celsius':' por cento')+' · '+stamp(r.date));
  el(field+'MiniOutput').textContent=number(r[field])+(field==='temp'?' °C':'%')+' · '+stamp(r.date);
  const cursor=el(field+'Spark').querySelector('.mini-cursor');if(cursor){cursor.setAttribute('cx',state.x(r));cursor.setAttribute('cy',state.y(r));}
 }
 function drawSparkline(id,field){
  const svg=el(id),range=el(field+'MiniRange'),rows=cleanRows(readings.slice(0,20)),previous=miniState[field];
  if(!rows.length){svg.replaceChildren();svg.setAttribute('aria-label','Ainda não há leituras para o gráfico');range.disabled=true;el(field+'MiniOutput').textContent='Aguardando leituras';el(field+'MiniScope').textContent='O gráfico aparece ao receber dados.';miniState[field]={rows};return;}
  const values=rows.map(r=>r[field]),min=Math.min(...values),max=Math.max(...values),positions=new Map(rows.map((r,i)=>[+r.date,i])),x=r=>rows.length===1?90:5+170*positions.get(+r.date)/(rows.length-1),y=r=>max===min?26:46-38*(r[field]-min)/(max-min),color=field==='temp'?'#a879f0':'#309dce';
  const groups=[[]];rows.forEach((r,i)=>{if(i&&r.date-rows[i-1].date>120000)groups.push([]);groups.at(-1).push(r);});
  svg.innerHTML='<path d="M5 47H175" class="mini-baseline"/>'+groups.filter(group=>group.length>1).map(group=>'<polyline points="'+group.map(r=>x(r)+','+y(r)).join(' ')+'" fill="none" stroke="'+color+'" stroke-width="2.3" stroke-linejoin="round"/>').join('')+rows.map(r=>'<circle cx="'+x(r)+'" cy="'+y(r)+'" r="2" fill="'+color+'"/>').join('')+'<circle class="mini-cursor" r="4" fill="'+color+'" stroke="var(--panel)" stroke-width="2"/>';
  svg.setAttribute('aria-label',(field==='temp'?'Temperatura':'Umidade')+': '+rows.length+' leituras; mínimo '+number(min)+', máximo '+number(max)+'. Use o controle abaixo para consultar cada horário.');
  let selected=previous?.follow===false?rows.findIndex(r=>+r.date===previous.selected):rows.length-1;if(selected<0)selected=rows.length-1;miniState[field]={rows,x,y,follow:true};range.max=rows.length-1;range.disabled=rows.length<2;selectMini(field,selected);
  el(field+'MiniScope').textContent=rows.length+' leitura'+(rows.length>1?'s':'')+(groups.length>1?' · pausas sem linha':'')+(Date.now()-rows.at(-1).date>120000?' · histórico':' · deslize');
 }
 function renderStationDetail(){const r=latest;el('stationDetail').textContent=valid(r)?'Última medição em '+stamp(r.date)+' (UTC−3).':'Aguardando a primeira medição.';}
 function renderTrend(){
  const result=trend(readings);el('trendResult').innerHTML=!result.available?`<p class="feature-empty">${result.reason}</p>`:['temp','hum'].map(field=>{const delta=result[field],flat=Math.abs(delta)<(field==='temp'?.5:2);return `<div><span>${field==='temp'?'Temperatura':'Umidade'}</span><strong class="${flat?'steady':delta>0?'rising':'falling'}">${flat?'→ Estável':delta>0?'↑ Em alta':'↓ Em queda'}</strong><small>${number(Math.abs(delta))} ${field==='temp'?'°C':'p.p.'} de variação em ${result.minutes} min</small></div>`;}).join('');
 }
 async function loadRecords(){
  const button=el('loadRecords');button.disabled=true;button.textContent='Consultando…';el('recordStatus').textContent='Buscando medições dos últimos 7 dias…';el('recordResults').replaceChildren();const key=StationHistory.dayKey(),start=StationHistory.shift(key,-6);
  try{
   const data=await fetchPeriod(start,StationHistory.shift(key,1),true);recordData=data;root.SiteExperience?.acceptWeek(data);document.querySelector('.records-panel h3').textContent=data.partial?'Destaques da amostra consultada':'Recordes dos últimos 7 dias';const values=records(data.items,StationHistory.dayKey);
   if(!values){el('recordStatus').textContent='Nenhuma medição encontrada nos últimos 7 dias. Você pode escolher outra data em Dados.';return;}
   const cards=[['Maior temperatura',number(values.max.temp)+' °C',stamp(values.max.date)],['Menor temperatura',number(values.min.temp)+' °C',stamp(values.min.date)],['Maior umidade',number(values.wet.hum)+'%',stamp(values.wet.date)],['Dia com maior média',StationHistory.bounds(values.hottest.key).start.toLocaleDateString('pt-BR',{timeZone:ZONE,day:'2-digit',month:'2-digit'}),number(values.hottest.temp)+' °C · '+values.hottest.count+' leituras']];
   el('recordResults').innerHTML=cards.map(([label,value,detail])=>`<div><span>${label}</span><strong>${value}</strong><small>${detail}</small></div>`).join('');
   el('recordStatus').textContent=`${data.items.length} leituras consultadas · ${start.split('-').reverse().join('/')} a ${key.split('-').reverse().join('/')} · UTC−3. ${data.partial?'Consulta limitada: estes são extremos da amostra, não recordes completos do período. ':'Extremos encontrados no período consultado. '}Médias por leitura; dias incompletos e lacunas afetam a comparação.`;
  }catch{recordData=null;el('recordStatus').textContent='Não foi possível consultar os recordes. Verifique sua conexão e tente novamente.';}finally{button.disabled=false;button.textContent='Atualizar 7 dias';}
 }
 api.queryRange=fetchPeriod;api.loadRecords=loadRecords;
 api.refresh=()=>{if(comparisonData&&comparisonData.endKey!==StationHistory.shift(StationHistory.dayKey(),1)){comparisonData=null;renderComparison();if((location.hash||'#dashboard')==='#dashboard'&&!compareBusy)loadComparison();}renderTrend();renderStationDetail();root.SiteExperience?.refresh();drawSparkline('tempSpark','temp');drawSparkline('humSpark','hum');if(mode==='hour'&&!compareBusy){if(comparisonData&&latest&&valid(latest)&&!comparisonData.items.some(r=>+r.date===+latest.date))comparisonData.items=[latest,...comparisonData.items];renderComparison();}};
 api.onNavigate=view=>{root.SiteExperience?.onNavigate(view);if(view==='dashboard'&&!compareBusy&&(!comparisonData||comparisonData.endKey!==StationHistory.shift(StationHistory.dayKey(),1)||Date.now()-comparisonData.at>60000))loadComparison();};
 api.answer=text=>{
  const extra=root.SiteExperience?.answer(text);if(extra)return extra;
  const m=recentMetrics(readings,Date.now(),comfortScore),scope=m?' Leitura de '+stamp(m.last.date)+(m.stale?', desatualizada.':'.'):'';
  if(/orvalho/.test(text))return m&&m.dew!==null?'O ponto de orvalho estimado é '+number(m.dew)+' °C. É a temperatura à qual o ar precisaria esfriar para começar a condensar vapor, mantendo sua umidade. Não prevê chuva.'+scope:'Ainda não há uma leitura válida na faixa de cálculo para estimar o ponto de orvalho.';
  if(/umidade absoluta|agua no ar|vapor de agua/.test(text))return m&&m.water!==null?'Há aproximadamente '+number(m.water)+' gramas de vapor em cada metro cúbico de ar, pela estimativa do painel.'+scope:'Preciso de uma leitura válida para estimar a quantidade de vapor no ar.';
  if(/ritmo|frequencia.*envio|intervalo.*envio/.test(text))return m&&m.cadence!==null?'O intervalo mediano entre envios próximos foi '+duration(m.cadence)+', considerando '+m.intervalCount+' intervalos carregados. Pausas maiores que dois minutos são analisadas separadamente.'+scope:'Ainda não há intervalos suficientes para avaliar o ritmo de envio.';
  if(/pausas|lacunas/.test(text))return m&&m.count>1?'Observei '+m.gapCount+' pausas maiores que dois minutos entre os registros carregados.'+(m.gapCount?' A maior foi de '+duration(m.longestGap)+'.':'')+' Isto descreve a amostra e não comprova uma falha do sensor.'+scope:'Preciso de mais registros para identificar pausas.';
  if(/melhor (hora|horario)|horario.*confort/.test(text))return m?.best?'Na amostra de '+m.day+', a hora com maior conforto médio foi '+m.best.hour+'h, com índice '+number(m.best.score)+'/100 em '+m.best.count+' leituras. Não é uma conclusão sobre o dia completo nem uma previsão.':'Ainda faltam leituras distribuídas no tempo para comparar o conforto por hora.';

  if(/compar|mais quente.*ontem/.test(text)){const data=compare(comparisonData?.items||readings,/ontem/.test(text)?'days':/manha|tarde/.test(text)?'shifts':mode);if(comparisonError||compareBusy||!data.a||!data.b)return 'Ainda não tenho medições suficientes confirmadas para comparar esses períodos. No Início, use O ambiente mudou? e toque em Atualizar.';return `${data.aLabel}: ${number(data.a.temp)} °C e ${number(data.a.hum)}%. ${data.bLabel}: ${number(data.b.temp)} °C e ${number(data.b.hum)}%. ${data.scope} ${data.stale?'As leituras são antigas. ':''}${comparisonData?.partial?'A consulta pode estar incompleta. ':''}${data.detail||''}`;}
  if(/recorde|maior temperatura.*semana|dia mais quente/.test(text)){if(!recordData)return 'No Início, toque em Consultar 7 dias para encontrar os maiores e menores valores registrados. Assim eu uso os dados consultados, em vez de adivinhar.';const r=records(recordData.items,StationHistory.dayKey);return r?'Nas leituras consultadas, a maior temperatura foi '+number(r.max.temp)+' °C em '+stamp(r.max.date)+'. '+(recordData.partial?'A amostra pode estar incompleta.':'O resultado cobre apenas o período consultado.'):'Não encontramos medições nesse período.';}
  if(/tendencia|esta subindo|esta caindo/.test(text)){const r=trend(readings);return r.available?'Nas últimas leituras, a temperatura variou '+number(r.temp)+' °C e a umidade '+number(r.hum)+' pontos percentuais em '+r.minutes+' minutos. Isso descreve uma mudança observada, não uma previsão.':r.reason;}
  return null;
 };
 document.querySelectorAll('[data-comparison]').forEach(button=>button.addEventListener('click',()=>{mode=button.dataset.comparison;document.querySelectorAll('[data-comparison]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));renderComparison();if(!comparisonData&&!compareBusy)loadComparison();}));
 el('comparisonRefresh').addEventListener('click',()=>loadComparison(true));el('loadRecords').addEventListener('click',loadRecords);
 el('learningSearch').addEventListener('input',()=>{const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),query=normalize(el('learningSearch').value.trim());let count=0;document.querySelectorAll('[data-learning]').forEach(card=>{card.hidden=!normalize(card.textContent).includes(query);if(!card.hidden)count++;});el('learningEmpty').hidden=count>0;});

 for(const field of ['temp','hum']){
  el(field+'MiniRange').addEventListener('input',event=>selectMini(field,Number(event.target.value),true));
  el(field+'Spark').addEventListener('pointerdown',event=>{const state=miniState[field];if(!state?.rows.length)return;const box=event.currentTarget.getBoundingClientRect(),target=(event.clientX-box.left)/box.width*180;let nearest=0;state.rows.forEach((r,i)=>{if(Math.abs(state.x(r)-target)<Math.abs(state.x(state.rows[nearest])-target))nearest=i;});selectMini(field,nearest,true);});
 }
 api.refresh();renderComparison();if((location.hash||'#dashboard')==='#dashboard')loadComparison();
})(typeof window!=='undefined'?window:globalThis);


/* Everyday experience: summaries, history, calendar and display preferences. */
(function(root){
 'use strict';
 const ZONE='America/Fortaleza',labels={heat:'Calor acima do limite',cold:'Frio abaixo do limite',dry:'Umidade baixa',wet:'Umidade alta',normal:'Sem alerta',gap:'Intervalo sem registros'};
 const fmt=n=>Number(n).toLocaleString('pt-BR',{maximumFractionDigits:1});
 const time=d=>d.toLocaleTimeString('pt-BR',{timeZone:ZONE,hour:'2-digit',minute:'2-digit'});
 const dateLabel=key=>StationHistory.bounds(key).start.toLocaleDateString('pt-BR',{timeZone:ZONE,day:'2-digit',month:'long',year:'numeric'});
 const hour=d=>Number(new Intl.DateTimeFormat('en-GB',{timeZone:ZONE,hour:'2-digit',hourCycle:'h23'}).format(d));
 function clean(items){const map=new Map();for(const r of items)if(r?.date instanceof Date&&Number.isFinite(+r.date)&&Number.isFinite(r.temp)&&r.temp>=-40&&r.temp<=80&&Number.isFinite(r.hum)&&r.hum>=0&&r.hum<=100&&+r.date<=Date.now()+30000&&!map.has(+r.date))map.set(+r.date,r);return [...map.values()].sort((a,b)=>a.date-b.date);}
 function conditions(r,t){const list=[];if(t.heat!==false&&r.temp>(t.maxTemp??30))list.push('heat');if(t.cold!==false&&r.temp<(t.minTemp??18))list.push('cold');if(t.humidity!==false&&r.hum<(t.minHum??30))list.push('dry');if(t.humidity!==false&&r.hum>(t.maxHum??70))list.push('wet');return list;}
 function aggregate(items){return items.length?{count:items.length,temp:items.reduce((s,r)=>s+r.temp,0)/items.length,hum:items.reduce((s,r)=>s+r.hum,0)/items.length,min:Math.min(...items.map(r=>r.temp)),max:Math.max(...items.map(r=>r.temp))}:null;}
 function dayModel(items,key,t={}){const rows=clean(items).filter(r=>StationHistory.dayKey(r.date)===key),hours=Array.from({length:24},(_,h)=>{const samples=rows.filter(r=>hour(r.date)===h),kinds=[...new Set(samples.flatMap(r=>conditions(r,t)))];return {hour:h,rows:samples,kind:samples.length?(kinds[0]||'normal'):'missing',kinds,...aggregate(samples)};}),periods=[[6,12,'Manhã'],[12,18,'Tarde'],[18,24,'Noite']].map(([from,to,label])=>({from,to,label,...aggregate(rows.filter(r=>hour(r.date)>=from&&hour(r.date)<to))}));return {key,rows,hours,periods,...aggregate(rows)};}
 function describe(model){if(!model.rows.length)return 'Não há medições confirmadas para este dia.';const [morning,afternoon]=model.periods;if(morning.count&&afternoon.count){const delta=afternoon.temp-morning.temp;return Math.abs(delta)<.5?'Manhã e tarde tiveram temperaturas médias parecidas nas leituras registradas.':'A tarde foi, em média, '+fmt(Math.abs(delta))+' °C '+(delta>0?'mais quente':'mais fria')+' que a manhã.';}return 'Nas medições deste dia, a temperatura variou de '+fmt(model.min)+' °C a '+fmt(model.max)+' °C, com umidade média de '+fmt(model.hum)+'%.';}
 function history(items,t){const rows=clean(items),events=[],open=new Map();let prev=null;for(const r of rows){const gap=prev&&r.date-prev.date>120000;if(gap){for(const ev of open.values()){ev.end=null;ev.reason='gap';events.push(ev);}open.clear();events.push({kind:'gap',start:new Date(+prev.date+120000),end:r.date,last:r.date,uncertain:true});}const active=conditions(r,t);for(const [kind,ev] of open){if(!active.includes(kind)){ev.end=r.date;ev.last=r.date;events.push(ev);open.delete(kind);}else ev.last=r.date;}for(const kind of active)if(!open.has(kind))open.set(kind,{kind,start:r.date,last:r.date,end:null,uncertain:!prev||!!gap});prev=r;}events.push(...open.values());return events.sort((a,b)=>b.start-a.start||a.kind.localeCompare(b.kind));}
 function traffic(r,now,connected,score){if(!r||!Number.isFinite(+r.date)||now-r.date>120000||!connected)return {state:'unknown',title:'Sem dados atuais',text:'Confira a última medição antes de avaliar o ambiente.'};const n=score(r.temp,r.hum);return n>=75?{state:'good',title:'Confortável',text:'Temperatura e umidade próximas das faixas de conforto do painel.'}:n>=50?{state:'attention',title:'Atenção',text:'Uma das condições se afastou da faixa de conforto do painel.'}:{state:'bad',title:'Desconfortável',text:'Temperatura ou umidade se afastaram bastante das faixas de referência.'};}
 const core={clean,conditions,aggregate,dayModel,describe,history,traffic};if(typeof module!=='undefined'&&module.exports){module.exports.experience=core;return;}
 const el=id=>document.getElementById(id),get=selector=>document.querySelector(selector),all=selector=>[...document.querySelectorAll(selector)];
 const readStore=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}},writeStore=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}};
 const defaults={history:true,lumi:true,comparisons:false,region:false,easy:false},saved=readStore('imnvlab-display',{}),prefs=Object.fromEntries(Object.entries(defaults).map(([k,v])=>[k,typeof saved[k]==='boolean'?saved[k]:v]));
 const previous=readStore('imnvlab-visit-v1',null);let baseline=previous&&Number.isFinite(previous.readingAt)&&Number.isFinite(previous.temp)&&Number.isFinite(previous.hum)?previous:null,day={key:StationHistory.dayKey(),items:[],state:'loading',partial:false},homeDay=null,selectedHour=null,weekData=null,calendarData=null,calendarMonth=StationHistory.dayKey().slice(0,7),monthRequest=0,alertRequest=0,alertData=null,alertFilter='all',alertLimit=30,reportUrl=null,lastSaved=0;
 const mount=(tag,cls,html)=>{const node=document.createElement(tag);node.className=cls;node.innerHTML=html;return node;};
 const dash=get('[data-view="dashboard"]'),dataPage=get('[data-view="dados"]'),alertsPage=get('[data-view="alertas"]'),morePage=get('[data-view="explorar"]');

 const toolbar=mount('div','home-tools',`<button class="text-link" type="button" data-open-report="home">Boletim visual</button><button class="text-link" type="button" id="openDisplay">Personalizar início</button>`);dash.querySelector('.campus-hero').after(toolbar);
 const focus=mount('section','panel focus-panel',`<div class="traffic-symbol" id="trafficSymbol" aria-hidden="true"></div><div class="focus-copy"><span class="eyebrow">COMO ESTÁ AGORA</span><h2 id="trafficTitle">Aguardando a estação</h2><p id="trafficText"></p><p id="priorityText" class="priority-text"></p><a id="priorityLink" class="text-link" href="#alertas">Ver detalhes →</a></div><div class="today-line"><span class="eyebrow">HOJE EM UMA FRASE</span><p id="homeDaySummary">Consultando as medições de hoje…</p><a href="#dados" class="text-link">Entender o dia →</a></div>`);dash.querySelector('.kpi-grid').after(focus);
 const visit=mount('details','visit-summary',`<summary>O que mudou desde minha última visita?</summary><p id="visitText"></p>`);visit.hidden=true;focus.after(visit);
 get('.chart-panel').dataset.homeCard='history';get('.insight-panel').dataset.homeCard='lumi';get('.discovery-grid').dataset.homeCard='comparisons';get('.hero-grid').dataset.homeCard='region';get('.hero-grid').previousElementSibling.dataset.homeCard='region';
 get('.chart-panel .card-title').append(mount('button','text-link', 'Lumi, explique'));get('.chart-panel .card-title button').type='button';get('.chart-panel .card-title button').dataset.guide='explique o gráfico recente';
 const tools=mount('details','panel display-options',`<summary>Deixe o site do seu jeito</summary><p>Os dados principais e os avisos de leitura antiga ficam sempre visíveis.</p><div class="display-grid"><fieldset><legend>Cartões no início</legend>${[['history','Gráfico das últimas leituras'],['lumi','Interpretação da Lumi'],['comparisons','Comparações e tendências'],['region','Panorama regional']].map(([key,label])=>`<label><input type="checkbox" data-display="${key}"> ${label}</label>`).join('')}</fieldset><fieldset><legend>Facilite a visualização</legend><label><input type="checkbox" data-display="easy"> Leitura fácil: letras e botões maiores</label><button type="button" class="outline-button" id="startPresentation">Modo apresentação</button><p>Ideal para TV ou sala de aula. Exibe apenas as informações principais.</p></fieldset></div><button type="button" class="text-link" id="resetDisplay">Voltar ao padrão</button><p id="displayStatus" role="status"></p>`);tools.id='displayOptions';morePage.append(tools);
 const dayStory=mount('article','panel day-story',`<div class="card-title"><div><span class="eyebrow" id="dayStoryDate"></span><h3>Como foi este dia?</h3></div><button class="text-link" type="button" data-open-report="day">Criar boletim</button></div><p id="dayStorySummary" role="status"></p><p id="dayStoryScope" class="feature-note"></p><div class="day-periods" id="dayPeriods"></div><details class="timeline-details"><summary>Ver a linha do tempo do dia</summary><p class="feature-note">Cada bloco resume as leituras daquela hora, usando seus limites atuais. Espaços vazios indicam falta de registros; a cor não descreve cada minuto.</p><div class="timeline-legend"><span class="heat">Calor</span><span class="cold">Frio</span><span class="dry">Umidade</span><span class="normal">Sem alerta</span><span class="missing">Sem dados</span></div><div class="hour-timeline" id="hourTimeline"></div><p id="hourDetail" class="feature-note" aria-live="polite">Toque em um horário para saber mais.</p></details><button class="text-link" type="button" data-guide="explique este dia">Lumi, explique este dia →</button>`);
 const tablePanel=dataPage.querySelector('.table-panel');tablePanel.before(dayStory);
 const calendar=mount('details','panel calendar-panel',`<summary>Escolher pelo calendário do mês</summary><div class="calendar-toolbar"><button type="button" class="outline-button" id="calendarPrev" aria-label="Mês anterior">←</button><h3 id="calendarTitle"></h3><button type="button" class="outline-button" id="calendarNext" aria-label="Próximo mês">→</button></div><p id="calendarStatus" class="feature-note" role="status"></p><div class="month-weekdays" aria-hidden="true"><span>Seg</span><span>Ter</span><span>Qua</span><span>Qui</span><span>Sex</span><span>Sáb</span><span>Dom</span></div><div id="monthGrid" class="month-grid"></div><button type="button" id="calendarRetry" class="text-link">Atualizar mês</button>`);dayStory.before(calendar);
 const week=mount('details','panel week-experience',`<summary>A semana em um gráfico</summary><p class="feature-note">Temperatura média das leituras de cada dia. Toque em uma barra para abrir a data.</p><div class="week-bars" id="weekBars"></div><p id="weekChartScope" class="feature-note" role="status">Abra para consultar os últimos 7 dias.</p>`);week.append(get('.records-panel'));dayStory.after(week);
 const raw=mount('details','raw-readings',`<summary>Ver todas as leituras e buscar horários</summary>`);tablePanel.before(raw);raw.append(tablePanel);
 const alertHistory=mount('details','panel alert-history',`<summary>Histórico de condições e retornos à faixa</summary><div class="history-controls"><label>Dia<input type="date" id="alertHistoryDate"></label><label>Mostrar<select id="alertHistoryFilter"><option value="all">Todos</option><option value="heat">Calor</option><option value="cold">Frio</option><option value="humidity">Umidade</option><option value="gap">Sem registros</option></select></label><button type="button" class="outline-button" id="reloadAlertHistory">Atualizar</button></div><p id="alertHistoryScope" class="feature-note" role="status"></p><div id="pastAlerts"></div><button type="button" class="text-link" id="morePastAlerts" hidden>Mostrar mais</button><details class="history-method"><summary>Como este histórico funciona?</summary><p>Reconstruímos condições a partir das leituras do dia e dos seus limites atuais. Não é um registro das configurações antigas nem de notificações entregues. Um retorno só é confirmado quando há uma leitura seguinte dentro da faixa; lacunas interrompem essa confirmação.</p></details>`);alertsPage.querySelector('.alert-layout').after(alertHistory);el('alertHistoryDate').value=StationHistory.dayKey();
 const help=mount('details','panel connection-help',`<summary>Estação sem atualizar? Vamos conferir</summary><p id="connectionDiagnosis" class="feature-note" role="status"></p><ol><li><strong>Confira a energia da estação.</strong><p>Verifique se o ESP32 está alimentado e se os cabos do sensor estão conectados.</p></li><li><strong>Confira as duas conexões.</strong><p>O seu aparelho e a estação precisam de internet. Veja se a rede Wi-Fi usada pelo ESP32 está disponível.</p></li><li><strong>Aguarde uma nova medição.</strong><p>Após reconectar, confira se o horário da última leitura mudou. A estação fica offline após 2 minutos sem leitura recente.</p></li></ol><button type="button" class="outline-button" id="checkConnection">Conferir novamente</button><p class="feature-note">Se continuar parada, peça à equipe responsável para verificar o envio no ESP32 e o acesso ao Firebase.</p>`);help.id='connectionHelp';alertsPage.append(help);
 const report=mount('dialog','report-dialog',`<header><div><span class="eyebrow">PRONTO PARA COMPARTILHAR</span><h2>Boletim visual</h2></div><button type="button" id="closeReport" aria-label="Fechar boletim">×</button></header><p id="reportStatus" role="status"></p><img id="reportPreview" alt="Boletim do IMNVLab com resumo do dia e limites da amostra" hidden><div class="report-actions"><button type="button" class="dark-button" id="saveReport" disabled>Baixar imagem PNG</button><button type="button" class="outline-button" id="copyReport" disabled>Copiar resumo</button><button type="button" class="text-link" id="reportChooseDay">Escolher outra data</button></div>`);report.id='reportDialog';document.body.append(report);
 const presentation=mount('section','presentation-view',`<header><div><img src="marca-ceti.jpeg?v=33" alt="CETI Nonato Valente"><strong>IMNVLab</strong></div><button type="button" class="outline-button" id="exitPresentation">Sair da apresentação · Esc</button></header><p id="presentationClock"></p><h1 id="presentationTitle"></h1><div class="presentation-metrics"><div><span>Temperatura</span><strong id="presentationTemp">—</strong></div><div><span>Umidade</span><strong id="presentationHum">—</strong></div><div><span>Conforto estimado</span><strong id="presentationComfort">—</strong></div></div><p id="presentationMessage"></p><p id="presentationSource"></p>`);presentation.id='presentationView';presentation.hidden=true;document.body.append(presentation);
 const days=new Map();let homeState='loading',reportText='',presentationActive=false;
 function applyDisplay(){for(const [key,value] of Object.entries(prefs)){all('[data-home-card="'+key+'"]').forEach(node=>node.hidden=!value);const input=get('[data-display="'+key+'"]');if(input)input.checked=value;}document.documentElement.classList.toggle('easy-reading',prefs.easy);get('.content-grid').classList.toggle('single-card',!prefs.history||!prefs.lumi);get('.content-grid').hidden=!prefs.history&&!prefs.lumi;requestAnimationFrame(()=>{historyChart?.resize();regionalMap?.invalidateSize();});}
 function modelFor(state){return dayModel(state?.items||[],state?.key||StationHistory.dayKey(),thresholds);}
 function scopeFor(state,model){return model.rows.length?model.rows.length+' leituras consultadas · '+time(model.rows[0].date)+'–'+time(model.rows.at(-1).date)+' · UTC−3. '+(state?.partial?'A consulta pode estar incompleta. ':'')+'Médias por leitura; lacunas não são preenchidas.':'Não calculamos médias nem preenchemos períodos sem registros.';}
 function setDay(state){day={...state,items:clean(state.items||[])};days.set(day.key,day);renderDay();if(day.key===StationHistory.dayKey()){homeDay=day;homeState=day.state;renderFocus();}}
 function renderDay(){const model=modelFor(day);el('dayStoryDate').textContent=dateLabel(day.key);el('dayStorySummary').textContent=day.state==='loading'?'Buscando as medições deste dia…':day.state==='error'?'Não foi possível consultar o dia. Use Tentar novamente acima.':describe(model);el('dayStoryScope').textContent=day.state==='ready'?scopeFor(day,model):'';el('dayPeriods').innerHTML=day.state!=='ready'?'':model.periods.map(p=>`<section><span>${p.label} · ${p.from}h–${p.to-1}h59</span><strong>${p.count?fmt(p.temp)+' °C':'Sem dados'}</strong><small>${p.count?fmt(p.hum)+'% de umidade · '+p.count+' leituras':'Nenhuma medição nesta faixa.'}</small></section>`).join('');el('hourTimeline').innerHTML=day.state!=='ready'?'':model.hours.map(h=>`<button type="button" data-hour="${h.hour}" class="hour-cell ${h.kind}" aria-pressed="${selectedHour===h.hour}" aria-label="${h.hour} horas: ${h.rows.length?labels[h.kind]+', '+h.rows.length+' leituras':'sem registros'}"><strong>${String(h.hour).padStart(2,'0')}h</strong><span>${h.rows.length?h.rows.length+' leit.':'—'}</span></button>`).join('');if(selectedHour!==null)showHour(selectedHour);else el('hourDetail').textContent='Toque em um horário para saber mais.';}
 function showHour(h){selectedHour=h;all('[data-hour]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.hour)===h)));const slot=modelFor(day).hours[h];el('hourDetail').textContent=slot?.rows.length?`${h}h–${h}h59: ${slot.rows.length} leituras, média de ${fmt(slot.temp)} °C e ${fmt(slot.hum)}% de umidade. ${slot.kinds.length?slot.kinds.map(k=>labels[k]).join('; '):'Sem alerta pelos limites atuais'}. Registros entre ${time(slot.rows[0].date)} e ${time(slot.rows.at(-1).date)}.`:'Nenhuma leitura registrada nesta hora. Isso não significa que o ambiente estava confortável.';}
 function renderFocus(){const r=clean(readings).at(-1),signal=traffic(r,Date.now(),navigator.onLine,comfortScore);focus.dataset.signal=signal.state;el('trafficTitle').textContent=signal.title;el('trafficText').textContent=signal.text;let message,href,label;if(signal.state==='unknown'){message='Prioridade: verificar por que as medições não estão chegando.';href='#alertas';label='Ajuda para reconectar →';}else{const kinds=conditions(r,thresholds);message=kinds.length?'Prioridade: '+labels[kinds[0]].toLowerCase()+'. Confira o valor e seus limites.':signal.state==='good'?'Nenhum limite configurado foi ultrapassado na última leitura.':'O conforto estimado merece atenção, mesmo sem um alerta pelos seus limites.';href=kinds.length?'#alertas':'#curiosidades';label=kinds.length?'Ver o que pede atenção →':'Entender o conforto →';}el('priorityText').textContent=message;el('priorityLink').href=href;el('priorityLink').textContent=label;el('homeDaySummary').textContent=homeState==='loading'?'Consultando as medições de hoje…':homeState==='error'?'Resumo de hoje indisponível. Consulte uma data em Dados.':describe(modelFor(homeDay));
  if(baseline&&r){visit.hidden=false;const fresh=clean(readings).filter(x=>+x.date>baseline.readingAt),newer=+r.date>baseline.readingAt;el('visitText').textContent=newer?`${fresh.length===100?'Pelo menos ':''}${fresh.length} novas leituras entre as carregadas desde sua última visita. A última temperatura mudou ${fmt(r.temp-baseline.temp)} °C e a umidade ${fmt(r.hum-baseline.hum)} pontos percentuais em relação à leitura que você viu antes. Última leitura: ${dateLabel(StationHistory.dayKey(r.date))}, ${time(r.date)}.${Date.now()-r.date>120000?' Ainda está desatualizada.':''}`:'Não há uma leitura mais nova do que a que você viu na visita anterior. Último registro: '+dateLabel(StationHistory.dayKey(r.date))+', '+time(r.date)+'.';}
  if(r&&Date.now()-lastSaved>30000){writeStore('imnvlab-visit-v1',{seenAt:Date.now(),readingAt:+r.date,temp:r.temp,hum:r.hum});lastSaved=Date.now();}
  el('connectionDiagnosis').textContent=!navigator.onLine?'Este aparelho está sem conexão com a internet.':r?Date.now()-r.date>120000?'A última leitura da estação é de '+dateLabel(StationHistory.dayKey(r.date))+', '+time(r.date)+'.':'A estação enviou uma leitura recente, às '+time(r.date)+'.':'Ainda não recebemos uma leitura válida. Confira energia, rede e envio da estação.';
  if(presentationActive)renderPresentation(r,signal);
 }
 async function ensureHome(){const key=StationHistory.dayKey();try{const result=await StationExplorer.queryRange(StationHistory.shift(key,-1),StationHistory.shift(key,1));acceptRange(result);}catch{homeState='error';renderFocus();}}
 function acceptRange(result){const today=StationHistory.dayKey();if(result.startKey<=today&&result.endKey>today){homeDay={key:today,items:result.items.filter(r=>StationHistory.dayKey(r.date)===today),state:'ready',partial:result.partial,at:result.at};homeState='ready';days.set(today,homeDay);if(day.key===today&&day.state!=='ready')setDay(homeDay);renderFocus();}}
 function renderWeek(result){weekData=result;const keys=Array.from({length:7},(_,i)=>StationHistory.shift(result.startKey,i)),stats=keys.map(key=>({key,...aggregate(result.items.filter(r=>StationHistory.dayKey(r.date)===key))})),values=stats.filter(s=>s.count).map(s=>s.temp),min=values.length?Math.min(0,...values):0,max=values.length?Math.max(...values,1):1;el('weekBars').innerHTML=stats.map(s=>`<button type="button" class="week-bar" data-date="${s.key}" aria-label="${dateLabel(s.key)}: ${s.count?fmt(s.temp)+' graus, '+s.count+' leituras':result.partial?'não localizado na amostra':'sem registros'}"><span>${StationHistory.bounds(s.key).start.toLocaleDateString('pt-BR',{timeZone:ZONE,weekday:'short'})}<small>${s.key.slice(8)}/${s.key.slice(5,7)}</small></span><i><b style="width:${s.count?Math.max(1,(s.temp-min)/(max-min)*100):0}%"></b></i><strong>${s.count?fmt(s.temp)+'°':'—'}</strong></button>`).join('');el('weekChartScope').textContent=`Escala de ${fmt(min)} a ${fmt(max)} °C. ${result.items.length} leituras consultadas; médias por leitura.${result.partial?' Amostra limitada: dias sem valores podem não ter sido alcançados pela consulta.':' Dias sem valores não têm registros nesta consulta.'}`;}
 function moveMonth(offset){const [y,m]=calendarMonth.split('-').map(Number),d=new Date(Date.UTC(y,m-1+offset,1,12));calendarMonth=d.toISOString().slice(0,7);loadMonth();}
 async function loadMonth(){const request=++monthRequest,key=calendarMonth+'-01',[y,m]=calendarMonth.split('-').map(Number),end=new Date(Date.UTC(y,m,1,12)).toISOString().slice(0,10);el('calendarTitle').textContent=StationHistory.bounds(key).start.toLocaleDateString('pt-BR',{timeZone:ZONE,month:'long',year:'numeric'});el('calendarNext').disabled=calendarMonth>=StationHistory.dayKey().slice(0,7);el('calendarStatus').textContent='Consultando este mês…';el('monthGrid').replaceChildren();try{const result=await StationExplorer.queryRange(key,end);if(request!==monthRequest)return;calendarData=result;const offset=(StationHistory.bounds(key).start.getUTCDay()+6)%7,total=new Date(Date.UTC(y,m,0)).getUTCDate();let markup='<span aria-hidden="true"></span>'.repeat(offset);for(let n=1;n<=total;n++){const date=calendarMonth+'-'+String(n).padStart(2,'0'),items=result.items.filter(r=>StationHistory.dayKey(r.date)===date),stats=aggregate(items),future=date>StationHistory.dayKey();markup+=`<button type="button" data-date="${date}" ${future?'disabled':''} aria-pressed="${date===day.key}" aria-label="${dateLabel(date)}: ${stats?fmt(stats.temp)+' graus de média':future?'data futura':result.partial?'sem valor na amostra':'sem registros'}"><b>${n}</b><span>${stats?fmt(stats.temp)+'°':future?'':'—'}</span></button>`;if(items.length)days.set(date,{key:date,items,state:'ready',partial:result.partial,at:result.at});}el('monthGrid').innerHTML=markup;el('calendarStatus').textContent=result.partial?'Médias da amostra consultada. Um traço pode significar que a data não foi alcançada pela consulta.':'Cada valor é a média das leituras do dia. Traço significa que não encontramos registros.';}catch{if(request===monthRequest)el('calendarStatus').textContent='Não foi possível consultar o mês. Toque em Atualizar mês para tentar novamente.';}}
 function chooseDate(key){if(!/^\d{4}-\d{2}-\d{2}$/.test(key))return;location.hash='#dados';navigate();selectedHour=null;el('historyDate').value=key;el('historyDate').dispatchEvent(new Event('change',{bubbles:true}));calendar.open=false;dayStory.scrollIntoView({behavior:'smooth',block:'start'});}
 async function loadAlertHistory(){const key=el('alertHistoryDate').value;if(!/^\d{4}-\d{2}-\d{2}$/.test(key))return;const request=++alertRequest;el('reloadAlertHistory').disabled=true;el('pastAlerts').replaceChildren();el('morePastAlerts').hidden=true;el('alertHistoryScope').textContent='Consultando condições registradas…';try{const known=days.get(key),result=known?.state==='ready'&&!known.partial&&Date.now()-known.at<60000?{items:known.items,partial:false,at:known.at}:await StationExplorer.queryRange(key,StationHistory.shift(key,1),true);if(request!==alertRequest)return;alertData={...result,key};alertLimit=30;renderAlertHistory();}catch{if(request===alertRequest){alertData=null;el('alertHistoryScope').textContent='Não foi possível consultar o histórico. Tente Atualizar novamente.';}}finally{if(request===alertRequest)el('reloadAlertHistory').disabled=false;}}
 function renderAlertHistory(){if(!alertData)return;const events=history(alertData.items,thresholds).filter(e=>alertFilter==='all'||e.kind===alertFilter||alertFilter==='humidity'&&['dry','wet'].includes(e.kind));el('alertHistoryScope').textContent=dateLabel(alertData.key)+' · '+alertData.items.length+' leituras · limites atuais. '+(alertData.partial?'Amostra limitada: eventos podem estar incompletos.':'Não é um histórico de notificações enviadas.');el('pastAlerts').innerHTML=events.slice(0,alertLimit).map(ev=>`<article class="past-alert ${ev.kind}"><span class="past-alert-dot" aria-hidden="true"></span><div><strong>${labels[ev.kind]}</strong><p>${ev.kind==='gap'?'Sem registros recentes entre '+time(ev.start)+' e '+time(ev.end)+'. Intervalo inferido das leituras.':(ev.uncertain?'Já presente na primeira leitura disponível às ':'Observado às ')+time(ev.start)+'. '+(ev.end?'Retorno à faixa observado às '+time(ev.end)+'.':ev.reason==='gap'?'Uma lacuna impede confirmar quando terminou.':'Sem retorno à faixa confirmado na amostra.')}</p></div></article>`).join('')||'<p class="feature-empty">'+(alertData.items.length?'Nenhuma condição corresponde ao filtro e aos limites atuais.':'Nenhuma leitura encontrada neste dia.')+'</p>';el('morePastAlerts').hidden=events.length<=alertLimit;}
 let presentationFocus=null,reportGeneration=0,reportName='IMNVLab-boletim.png';
 function renderPresentation(r,signal){el('presentationClock').textContent=new Date().toLocaleString('pt-BR',{timeZone:ZONE,dateStyle:'full',timeStyle:'short'})+' · UTC−3';el('presentationTitle').textContent=signal.title;presentation.dataset.signal=signal.state;el('presentationTemp').textContent=r?fmt(r.temp)+' °C':'—';el('presentationHum').textContent=r?fmt(r.hum)+'%':'—';el('presentationComfort').textContent=r?comfortScore(r.temp,r.hum)+'/100':'—';el('presentationMessage').textContent=signal.state==='unknown'?'Leitura antiga ou conexão indisponível. Estes valores não confirmam o ambiente agora.':el('priorityText').textContent;el('presentationSource').textContent=r?'Última medição: '+dateLabel(StationHistory.dayKey(r.date))+', '+time(r.date)+'.':'Aguardando medições da estação.';}
 async function enterPresentation(){presentationFocus=document.activeElement;presentationActive=true;presentation.hidden=false;presentation.setAttribute('role','dialog');presentation.setAttribute('aria-modal','true');presentation.setAttribute('aria-label','Apresentação da estação');document.body.classList.add('is-presenting');for(const child of document.body.children)if(child!==presentation&&child.tagName!=='SCRIPT'){child.dataset.presentationInert=String(child.inert);child.inert=true;}renderFocus();el('exitPresentation').focus();try{await presentation.requestFullscreen?.();}catch{/* Overlay remains usable when full screen is unavailable. */}}
 function exitPresentation(){if(!presentationActive)return;presentationActive=false;presentation.hidden=true;document.body.classList.remove('is-presenting');all('[data-presentation-inert]').forEach(node=>{node.inert=node.dataset.presentationInert==='true';delete node.dataset.presentationInert;});if(document.fullscreenElement===presentation)document.exitFullscreen().catch(()=>{});presentationFocus?.focus();}
 function wrap(ctx,text,x,y,width,line=38){let row='';for(const word of text.split(/\s+/)){const next=row?row+' '+word:word;if(ctx.measureText(next).width>width&&row){ctx.fillText(row,x,y);y+=line;row=word;}else row=next;}if(row)ctx.fillText(row,x,y);return y+line;}
 function openReport(which){const generation=++reportGeneration,state=which==='day'?day:homeDay;el('reportPreview').hidden=true;el('saveReport').disabled=el('copyReport').disabled=true;reportText='';if(reportUrl){URL.revokeObjectURL(reportUrl);reportUrl=null;}if(!report.open)report.showModal();const model=state&&modelFor(state);if(!state||state.state!=='ready'||!model.rows.length){el('reportStatus').textContent='Ainda não há medições confirmadas para esta data. Escolha em Dados um dia com registros para criar o boletim.';return;}const scope=scopeFor(state,model),summary=describe(model),title=dateLabel(state.key),last=model.rows.at(-1),today=state.key===StationHistory.dayKey(),outdated=today&&Date.now()-last.date>120000;
 reportText=['IMNVLab · Boletim de '+title,summary,'Temperatura média: '+fmt(model.temp)+' °C · Umidade média: '+fmt(model.hum)+'%','Mínima: '+fmt(model.min)+' °C · Máxima: '+fmt(model.max)+' °C',...model.periods.map(p=>p.label+': '+(p.count?fmt(p.temp)+' °C / '+fmt(p.hum)+'%':'sem medições')),scope,outdated?'A última leitura de hoje está desatualizada.':'Resumo histórico das leituras; não é previsão.'].join('\n');
 const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1200;const c=canvas.getContext('2d');c.fillStyle='#f0f5ff';c.fillRect(0,0,1080,1200);c.fillStyle='#244f84';c.fillRect(0,0,1080,180);c.fillStyle='#fff';c.font='bold 46px sans-serif';c.fillText('IMNVLab',58,78);c.font='25px sans-serif';c.fillText('O ambiente em palavras simples',58,123);c.fillStyle='#263955';c.font='bold 30px sans-serif';wrap(c,title,58,240,960,38);c.font='27px sans-serif';wrap(c,summary,58,309,960,38);c.fillStyle='#fff';c.fillRect(48,405,984,250);c.fillStyle='#66728a';c.font='24px sans-serif';c.fillText('TEMPERATURA MÉDIA',78,458);c.fillText('UMIDADE MÉDIA',587,458);c.fillStyle='#6642bd';c.font='bold 66px sans-serif';c.fillText(fmt(model.temp)+' °C',78,544);c.fillStyle='#197daf';c.fillText(fmt(model.hum)+'%',587,544);c.fillStyle='#53647c';c.font='25px sans-serif';c.fillText('Mínima '+fmt(model.min)+' °C  ·  Máxima '+fmt(model.max)+' °C',78,610);c.font='bold 28px sans-serif';c.fillStyle='#263955';c.fillText('Ao longo do dia',58,716);model.periods.forEach((p,i)=>{const x=58+i*330;c.fillStyle='#66728a';c.font='24px sans-serif';c.fillText(p.label,x,768);c.fillStyle='#263955';c.font='bold 31px sans-serif';c.fillText(p.count?fmt(p.temp)+' °C':'Sem dados',x,816);c.font='22px sans-serif';if(p.count)c.fillText(fmt(p.hum)+'% de umidade',x,856);});c.fillStyle='#53647c';c.font='23px sans-serif';let y=wrap(c,scope,58,931,960,32);c.fillStyle=outdated?'#96601b':'#53647c';wrap(c,outdated?'Atenção: a última leitura de hoje está desatualizada.':'Resumo das medições disponíveis. Não é previsão do tempo.',58,y+24,960,32);c.fillStyle='#6642bd';c.fillRect(58,1135,964,3);c.font='22px sans-serif';c.fillText('CETI Nonato Valente · Canto do Buriti, PI',58,1174);
 reportName='IMNVLab-boletim-'+state.key+'.png';canvas.toBlob(blob=>{if(generation!==reportGeneration||!report.open)return;if(!blob){el('reportStatus').textContent='Não foi possível gerar a imagem. Tente novamente.';return;}reportUrl=URL.createObjectURL(blob);el('reportPreview').src=reportUrl;el('reportPreview').hidden=false;el('saveReport').disabled=el('copyReport').disabled=false;el('reportStatus').textContent='Confira o resumo antes de compartilhar. '+(state.partial?'Esta consulta tem amostra limitada.':'Os valores são médias das leituras do dia.');},'image/png');
 }
 function answer(text){const q=String(text).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(/explique.*grafico|entend.*grafico/.test(q)){const rows=clean(readings).slice(-20),r=rows.at(-1);return rows.length?'O gráfico recente mostra '+rows.length+' leituras, de '+time(rows[0].date)+' a '+time(r.date)+', em '+dateLabel(StationHistory.dayKey(r.date))+'. A temperatura variou de '+fmt(Math.min(...rows.map(x=>x.temp)))+' a '+fmt(Math.max(...rows.map(x=>x.temp)))+' °C. A umidade variou de '+fmt(Math.min(...rows.map(x=>x.hum)))+' a '+fmt(Math.max(...rows.map(x=>x.hum)))+'%. Cada ponto é uma medição; os minigráficos têm um controle para explorar os horários.'+(Date.now()-r.date>120000?' São registros antigos, não as condições atuais.':''):'Ainda não tenho leituras para explicar o gráfico. Abra Dados para consultar outra data.';}
 if(/explique.*(dia|data)|entend.*(dia|data)/.test(q)){const m=modelFor(day);return day.state==='ready'?dateLabel(day.key)+': '+describe(m)+' '+(m.rows.length?scopeFor(day,m):'Escolha outra data no calendário de Dados.'):'Estou sem uma consulta confirmada para esse dia. Abra Dados e aguarde as medições.';}
 if(/boletim|compartilh/.test(q))return 'Vamos transformar os dados em um boletim? No Início, toque em Boletim visual. Para outra data, entre em Dados, escolha o dia e toque em Criar boletim. Você pode baixar uma imagem ou copiar o resumo.';
 if(/historico.*alert|alert.*historico/.test(q))return 'Em Alertas, abra Histórico de condições e retornos à faixa, escolha o dia e filtre por calor, frio ou umidade. Ele usa as leituras e seus limites atuais; uma pausa no envio não confirma que o ambiente voltou à faixa.';
 if(/calendario|linha do tempo/.test(q))return 'Em Dados, escolha uma data pelo calendário. Em Como foi este dia, abra a linha do tempo e toque em um horário. Eu mostro as leituras daquele período; espaços sem registros ficam identificados.';
 if(/ultima visita|o que mudou/.test(q))return baseline?el('visitText').textContent:'Na próxima visita, vou comparar a última leitura que você viu com a mais recente. Essa lembrança fica somente neste navegador.';
 if(/apresentacao|leitura facil|personaliz/.test(q))return 'Abra Mais → Deixe o site do seu jeito. Lá você escolhe os cartões do Início, ativa letras maiores ou abre o modo apresentação para mostrar os dados em uma TV.';
 return null;}
 root.SiteExperience={acceptDay:setDay,acceptRange,acceptWeek:renderWeek,answer,refresh(){renderFocus();const today=StationHistory.dayKey();if(homeDay&&homeDay.key!==today){homeDay=null;homeState='loading';ensureHome();}else if(homeDay?.state==='ready'){const rows=clean([...homeDay.items,...readings.filter(r=>StationHistory.dayKey(r.date)===today)]);if(rows.length!==homeDay.items.length||+rows.at(-1)?.date!==+homeDay.items.at(-1)?.date){homeDay={...homeDay,items:rows};renderFocus();}}},onNavigate(view){if(view==='dados')renderDay();renderFocus();}};
 el('openDisplay').addEventListener('click',()=>{location.hash='#explorar';navigate();tools.open=true;tools.scrollIntoView({behavior:'smooth'});});
 all('[data-display]').forEach(input=>input.addEventListener('change',()=>{prefs[input.dataset.display]=input.checked;const saved=writeStore('imnvlab-display',prefs);applyDisplay();el('displayStatus').textContent=saved?'Preferências salvas neste navegador.':'A escolha vale nesta sessão; o navegador não permitiu salvar.';}));
 el('resetDisplay').addEventListener('click',()=>{Object.assign(prefs,defaults);writeStore('imnvlab-display',prefs);applyDisplay();el('displayStatus').textContent='Visualização padrão restaurada.';});
 el('startPresentation').addEventListener('click',enterPresentation);el('exitPresentation').addEventListener('click',exitPresentation);document.addEventListener('keydown',event=>{if(presentationActive&&event.key==='Escape')exitPresentation();});document.addEventListener('fullscreenchange',()=>{if(presentationActive&&!document.fullscreenElement)exitPresentation();});
 calendar.addEventListener('toggle',()=>{if(calendar.open&&!calendarData)loadMonth();});el('calendarPrev').addEventListener('click',()=>moveMonth(-1));el('calendarNext').addEventListener('click',()=>moveMonth(1));el('calendarRetry').addEventListener('click',loadMonth);
 week.addEventListener('toggle',()=>{if(week.open&&!weekData){el('weekChartScope').textContent='Consultando as leituras da semana…';Promise.resolve(StationExplorer.loadRecords()).then(()=>{if(!weekData)el('weekChartScope').textContent='Consulta indisponível. Use Consultar últimos 7 dias abaixo para tentar novamente.';});}});
 document.addEventListener('click',event=>{const button=event.target.closest('[data-date]');if(button&&!button.disabled)chooseDate(button.dataset.date);const bulletin=event.target.closest('[data-open-report]');if(bulletin)openReport(bulletin.dataset.openReport);});
 el('hourTimeline').addEventListener('click',event=>{const button=event.target.closest('[data-hour]');if(button)showHour(Number(button.dataset.hour));});
 alertHistory.addEventListener('toggle',()=>{if(alertHistory.open&&!alertData)loadAlertHistory();});el('alertHistoryDate').max=StationHistory.dayKey();el('alertHistoryDate').addEventListener('change',loadAlertHistory);el('reloadAlertHistory').addEventListener('click',loadAlertHistory);el('alertHistoryFilter').addEventListener('change',event=>{alertFilter=event.target.value;alertLimit=30;renderAlertHistory();});el('morePastAlerts').addEventListener('click',()=>{alertLimit+=30;renderAlertHistory();});
 document.addEventListener('limits-saved',()=>{renderDay();renderAlertHistory();renderFocus();});el('priorityLink').addEventListener('click',()=>{if(focus.dataset.signal==='unknown')help.open=true;});
 el('checkConnection').addEventListener('click',async()=>{const button=el('checkConnection');button.disabled=true;el('connectionDiagnosis').textContent='Conferindo a conexão com a estação…';let timer;try{await Promise.race([db.collection('leituras').orderBy('timestamp','desc').limit(1).get({source:'server'}),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('timeout')),10000);})]);renderFocus();el('connectionDiagnosis').textContent+=' A consulta ao servidor respondeu.';}catch{el('connectionDiagnosis').textContent='Não conseguimos consultar o servidor agora. Confira a internet deste aparelho e tente novamente.';}finally{clearTimeout(timer);button.disabled=false;}});
 el('closeReport').addEventListener('click',()=>report.close());report.addEventListener('close',()=>{reportGeneration++;if(reportUrl){URL.revokeObjectURL(reportUrl);reportUrl=null;}});el('reportChooseDay').addEventListener('click',()=>{report.close();location.hash='#dados';});el('saveReport').addEventListener('click',()=>{if(!reportUrl)return;const link=document.createElement('a');link.href=reportUrl;link.download=reportName;link.click();});el('copyReport').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(reportText);el('reportStatus').textContent='Resumo copiado. Cole onde quiser compartilhar.';}catch{el('reportStatus').textContent='Não foi possível copiar. Você ainda pode baixar a imagem PNG.';}});
 addEventListener('pagehide',()=>{const r=clean(readings).at(-1);if(r)writeStore('imnvlab-visit-v1',{seenAt:Date.now(),readingAt:+r.date,temp:r.temp,hum:r.hum});});
 applyDisplay();renderDay();renderFocus();ensureHome();
})(typeof window!=='undefined'?window:globalThis);
/* School scenes with a minimal pause control. */
(function setupSchoolGallery(){
 if(typeof document==='undefined')return;
 const hero=document.querySelector('.campus-hero');if(!hero)return;
 const scenes=[['fachada','Nossa escola','58% 48%'],['entrada','Bem-vindos ao CETI','55% 48%'],['biblioteca','Descobertas na biblioteca','48% 38%'],['sala','Aprender em sala','58% 45%'],['informatica','Tecnologia e descobertas','56% 43%'],['xadrez','Aprender juntos','55% 47%']];
 const layer=document.createElement('div');layer.className='hero-scenes';layer.setAttribute('aria-hidden','true');const images=scenes.map(([file,label,position],i)=>{const image=document.createElement('img');image.alt='';image.decoding='async';image.style.objectPosition=position;if(i===0){image.src='assets/escola-'+file+'.jpeg';image.className='active';image.fetchPriority='high';}layer.append(image);return image;});hero.prepend(layer);
 const controls=document.createElement('div');controls.className='hero-gallery-controls';controls.setAttribute('role','group');controls.setAttribute('aria-label','Imagens da escola');controls.innerHTML='<button type="button" id="heroPause"></button>';hero.append(controls);hero.querySelector('.illustration-label').textContent='Ilustrações do ambiente escolar';
 const motion=matchMedia('(prefers-reduced-motion: reduce)'),pause=document.getElementById('heroPause');let current=0,requested=0,request=0,interval,paused=motion.matches||!!navigator.connection?.saveData,hover=false,focused=false,visible=true;const failed=new Set();
 function sync(){clearTimeout(interval);pause.textContent=paused?'▶':'Ⅱ';pause.setAttribute('aria-label',paused?'Retomar troca automática':'Pausar troca automática');pause.setAttribute('aria-pressed',String(paused));if(!paused&&!hover&&!focused&&visible&&!document.hidden&&(!location.hash||location.hash==='#dashboard'))interval=setTimeout(()=>change(next(1)),7000);}
 function next(direction){let i=requested;for(let n=0;n<scenes.length;n++){i=(i+direction+scenes.length)%scenes.length;if(!failed.has(i))return i;}return current;}
 async function change(index){requested=index;const token=++request;clearTimeout(interval);const image=images[index];try{if(!image.getAttribute('src'))image.src='assets/escola-'+scenes[index][0]+'.jpeg';await image.decode();if(token!==request)return;images.forEach((img,i)=>img.classList.toggle('active',i===index));current=index;hero.dataset.scene=String(index);failed.delete(index);}catch{if(token!==request)return;failed.add(index);}finally{if(token===request)sync();}}
 pause.addEventListener('click',()=>{paused=!paused;sync();});hero.addEventListener('mouseenter',()=>{hover=true;sync();});hero.addEventListener('mouseleave',()=>{hover=false;sync();});hero.addEventListener('focusin',()=>{focused=true;sync();});hero.addEventListener('focusout',()=>{setTimeout(()=>{focused=hero.contains(document.activeElement);sync();},0);});document.addEventListener('visibilitychange',sync);addEventListener('hashchange',sync);motion.addEventListener('change',event=>{if(event.matches)paused=true;sync();});if('IntersectionObserver' in window)new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;sync();}).observe(hero);hero.dataset.scene='0';sync();
})();
